name: Sync to Hugging Face
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.Cancer_Research }}
        run: git push --force https://pennywa:$Cancer_Research@huggingface.co/spaces/pennywa/Cancer_Research_Agent main

        
